
###
POST http://localhost:8080/agent/clients/ajouter
Cache-Control: no-cache
Content-Type: application/json

{
    "nom": "Bouzid",
    "prenom": "Sara",
    "email": "sara@gmailos.com"
}

###

POST http://localhost:8080/agent/clients/8/comptes/ajouter/
Cache-Control: no-cache
Content-Type: application/json

{
    "intitule": "M. DAOULAT KHALIL",
    "solde": 500
}

###

GET http://localhost:8080/agent/clients/

###

GET http://localhost:8080/agent/profile/4

###



