
###
POST http://localhost:8080/agent/clients/ajouter
Cache-Control: no-cache
Content-Type: application/json

{
    "nom": "Bouzid",
    "prenom": "Sara",
    "email": "sara@gmailos.com"
}

###

POST http://localhost:8080/agent/clients/1/comptes/ajouter/
Cache-Control: no-cache
Content-Type: application/json

{
    "intitule": "Mme. SARA BOUZID",
    "solde": 600
}

###

GET http://localhost:8080/agent/clients/

###

GET http://localhost:8080/agent/profile/4

###

GET http://localhost:8080/client/api/1/comptes

###

POST http://localhost:8080/client/api/recharges/create
Cache-Control: no-cache
Content-Type: application/json

{
    "numeroCompte": "2442365958750258",
    "montant": 500,
    "operateur": "orange",
    "codeSecret": 82417748,
    "numeroTelephone": "NMRA DIAL SAHBTI"
}

###

POST http://localhost:8080/client/api/virements/create
Cache-Control: no-cache
Content-Type: application/json

{
    "numeroCompte": "2442365958750258",
    "numeroCompteDest": "2226101696931450",
    "montant": 120,
    "notes": "WA FLOOOSSSI",
    "codeSecret": 82417748
}

###

GET http://localhost:8080/client/api/1/virements

###

POST http://localhost:8080/client/api/virements/1/confirm
Cache-Control: no-cache
Content-Type: application/json

{
    "codeVerification": 52031022
}

###

POST http://localhost:8080/client/api/verify_number
Cache-Control: no-cache
Content-Type: application/json

{
    "numeroCompte": 2226101696931450
}

###

PUT http://localhost:8080/client/api/comptes/block
Cache-Control: no-cache
Content-Type: application/json

{
    "numeroCompte": 2442365958750258,
    "codeSecret": 82417748
}

###

POST http://localhost:8080/client/api/comptes/suspend
Cache-Control: no-cache
Content-Type: application/json

{
    "numeroCompte": 2442365958750258,
    "codeSecret": 82417748
}

###

DELETE http://localhost:8080/client/api/virements/1/delete

###

GET http://localhost:8080/client/api/1/notifications/

###

DELETE http://localhost:8080//comptes/{id}/supprimer

###
# API to test notifications (check http://localhost:8080/admin)
POST http://localhost:8080/client/api/notification
Content-Type: application/json

{
    "contenu": "salut <3"
}

###
